### ISSUE TITLE
ACF Composer not registering in Sage 10.0.0-beta.2

### ISSUE THREAD

**Issue by ajcsilva** [Log1x/acf-composer#101]
With the latest 10.0.0-beta.2 update to Sage, it seems that acf-composer is not registering with Acorn. I'm not well-versed in the internals, but, it looks like Sage is using Acorn v2.0.0-beta.6 and maybe that is causing some breaking changes.

**Comment by Log1x** [comment]
This should be fixed upstream in https://github.com/roots/acorn/pull/155
