### ISSUE TITLE
Feature request: Templates for ACF Blocks

### ISSUE THREAD

**Issue by SergiArias** [Log1x/acf-composer#103]
I am constantly composing blocks for ACF, and removing parts that I don't normally use. So I think it would be nice to be able to store a few templates and compose from there.
Right now I am editing src/Console/stubs/block.construct.stub in each project to use my own template, but I think it's not as elegant as it should be.

**Comment by Log1x** [comment]
What directory structure do you have in mind for this?

**Comment by SergiArias** [comment]
For me, what it would make sense is a folder in config called acf-composer-templates. Or else, an array of options inside poet, be it to choose which methods to generate or directly point to the stub file if we want something more customized.

What do you think about it?

**Comment by mrmadhat** [comment]
> What directory structure do you have in mind for this?

How about config/stubs/acf-composer?
