### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by mans-papaja** [Log1x/acf-composer#106]
Hey, first and foremost I must say that I love acf-composer! 😍

I've been trying to get localization a go recently and seem to be hitting a wall when trying to localize my blocks and options created with acf-composer. Option pages created without using acf-composer works as well as the fields declared in the acf-composer created options files.

I've used the __construct mentioned in the docs for both blocks and option pages:

```
<?php

namespace App\Options;

use Log1x\AcfComposer\Options as Field;
use Roots\Acorn\Application;
use StoutLogic\AcfBuilder\FieldsBuilder;

class General extends Field
{
    public function __construct(Application $app)
    {
        /**
         * The option page menu name.
         *
         * @var string
         */
        $this->name = __('Footer', 'sage');
        parent::__construct($app);
    }

    /**
     * The option page field group.
     *
     * @return array
     */
    public function fields()
    {
        $general = new FieldsBuilder('general');
        $general
            ->addText('title', [
                'label' => __('Title', 'sage'),
            ]);
        return $general->build();
    }
}
```

I've spent a good amount of time trying to figure out what it could be but seems to have hit a wall. Any suggestions on how to solve it or is this something that isn't supported in acf-composer? 😊

**Comment by Log1x** [comment]
Did you ever figure this out? What you provided I _think_ should work.

**Comment by mans-papaja** [comment]
Sorry for the late reply. No I actually never did get this to work ☺️

**Comment by mans-papaja** [comment]
<img width="281" alt="Screenshot 2022-09-19 at 17 26 40" src="https://user-images.githubusercontent.com/51531751/191054515-d943f069-68a8-4b23-9c0d-7fa38b3dd3a4.png">
 @Log1x to be clear the only thing that I was not able to translate was the block title and block description, shown in image, as well as option title.

**Comment by kjvdven** [comment]
I was trying this again, but still can't get this to work. 

Has this to do with the block name and title is set with Javascript and there aren't generated any json translation files? Because the command to generate the .pot file (`wp i18n make-pot`) doesn't find any .js file where the name is being used. 

Or isn't that related at all?

**Comment by gol4nsky** [comment]
Hi, Is there any solution with localization ? Using --construct and everything according to this https://roots.io/sage/docs/localization/#localization, the strings still appear in the originally encoded language and not translated.
