### ISSUE TITLE
Docs: add note about Block Supports

### ISSUE THREAD

**Issue by mike-sheppard** [Log1x/acf-composer#107]
**Note**: popping this here until I have time to submit a PR (or someone else beats me to it 🙏 )

Didn't know this until reading it [in this PR](https://github.com/AdvancedCustomFields/acf/issues/602#issuecomment-1027885133) but ACF Blocks supports all [native Block Supports](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/) including `color`, `typography`, `spacing` etc

```php
...
    public $supports = [
        'align'         => true,
        'jsx'           => true,
        ...
        'color'         => [
            'text'       => true,
            'background' => true,
        ],
        'spacing'       => [
            'margin'  => true,
            'padding' => true,
        ],
    ];
...
```

![2022-02-02 1552 - Google Chrome](https://user-images.githubusercontent.com/1690006/154309568-7ffeb219-9b51-43b7-84c5-76d39a7c0fa7.jpg)

![2022-02-02 1554 - Google Chrome](https://user-images.githubusercontent.com/1690006/154309749-f239d6a7-1440-4c31-80c3-f5923deaa03e.jpg)

**Comment by Log1x** [comment]
nice!

**Comment by squareone-jarrod** [comment]
Thanks for this! Been searching everywhere to see if it was possible.

**Comment by colinswinney** [comment]
After adding color support to your block.php file, how do you pass that into {{ $block->classes }}?  I'm not seeing "has-primary-color" on the front end, though I do see it get added to the block when I inspect the editor.

**Comment by mike-sheppard** [comment]
hey @colinswinney it isn't currently handled by ACF Composer or ACF for that matter so you'll need to construct the class names with the slugs returned in `$block->block->backgroundColor` & `$block->block->textColor`

**Comment by mike-sheppard** [comment]
a very quick and dirty example to get you started, you'll need to check they exist etc
```blade
<div class="has-{{ $block->block->backgroundColor }}-background-color has-background">
```

**Comment by colinswinney** [comment]
Fantastic, thanks @mike-sheppard !  I appreciate it!

**Comment by daverobertson** [comment]
If it helps anyone, here's a method I've been using to prepare the text and background color classes for the block's view.

in the block's class file:
```
/**
 * Assembles the block's text and background color classes
 *
 * @return string
 */
public function getColorClasses()
{
    // No need to generate them if we're inside the Editor:
    if ($this->preview) {
        return '';
    }

    $classes = [];

    $bgColor = $this->block->backgroundColor ?? null;
    if (!empty($bgColor)) {
        $classes[] = sprintf('has-background has-%s-background-color', $bgColor);
    }

    $textColor = $this->block->textColor ?? null;
    if (!empty($textColor)) {
        $classes[] = sprintf('has-%s-color', $textColor);
    }

    return implode(' ', $classes);
}
```

send it to the view via the with() method:

```
public function with()
{
    return [
        /* ... */
        'colorClasses' => $this->getColorClasses(),
    ];
}
```

and in the accompanying blade template, via the new-ish [@class directive](https://laravel.com/docs/9.x/blade#conditional-classes), we can simply use:

`<div @class([$block->classes, $colorClasses])>`

It would be neater just to append to $block->classes, but not sure how that could be done... or better yet, if ACF would just do it for us :) HTH!

**Comment by Log1x** [comment]
If anyone wants to do a PR adding these to the block stub `$supports` as well as using some of the logic from @daverobertson's post above to add the classes to [`$block->classes`](https://github.com/Log1x/acf-composer/blob/master/src/Block.php#L334-L353) as needed it'd be super appreciated. ❤️

**Comment by Log1x** [comment]
#145
