### ISSUE TITLE
Grabbing data from menu item

### ISSUE THREAD

**Issue by minemindmedia** [Log1x/acf-composer#108]
Does anyone know how to grab the data from an ACF menu item and display it while using Navi?
(https://github.com/Log1x/navi)

For example, I've successfully added a simple text input to each menu item:

```
<?php

namespace App\Fields;

use Log1x\AcfComposer\Field;
use StoutLogic\AcfBuilder\FieldsBuilder;

class Menus extends Field
{
    /**
     * The field group.
     *
     * @return array
     */
    public function fields()
    {
        $menus = new FieldsBuilder('menus');

        $menus
            ->setLocation('nav_menu_item', '==', 'all');

        $menus
            ->addText('subtext', [
                'label' => 'Sub-text'
            ]);

        return $menus->build();
    }
}
```

<img width="435" alt="image" src="https://user-images.githubusercontent.com/8854361/157573145-9c81fb52-1583-435a-bf69-6df668b04474.png">

I am attempting to pull that input data to the menus under the menu title but can't quite determine how to do so.

The documentation from ACF for Displaying Fields requires setting up a function for [wp_nav_menu_objects](https://developer.wordpress.org/reference/hooks/wp_nav_menu_objects/) but that doesn't work using Brandon's Navi package.

https://www.advancedcustomfields.com/resources/adding-fields-menu-items/

**Comment by Log1x** [comment]
https://github.com/Log1x/navi#accessing-custom-fields this should work I think.

**Comment by minemindmedia** [comment]
Actually, that doesn't appear to return anything.
This however returns the site title:

`{{ get_field('subtext', $item->id) ?: $item->label }}`
