### ISSUE TITLE
No publishable resources for tag [].

### ISSUE THREAD

**Issue by tomhayes** [Log1x/acf-composer#110]
Hi, 

When I try and run `wp acorn vendor:publish --provider="Log1x\AcfComposer\Providers\AcfComposerServiceProvider"` I get the following: 

```
No publishable resources for tag [].
Publishing complete.
```

I tried running `wp acorn acf:field Example` afterwards (as it did say complete), but then I get the error: 

```
There are no commands defined in the "acf" namespace.  
```

I'm not really sure what I'm missing - can anyone shed any light on this? This is my first time using acf-composer and acorn on a project. 

Thanks in advance!

**Comment by Log1x** [comment]
Try running `wp acorn package:discover` (from #109) – outside of that, I can't produce this issue on any of my sites in any environment.
