### ISSUE TITLE
How can I log errors?

### ISSUE THREAD

**Issue by Monokai** [Log1x/acf-composer#117]
Hi, I'm working on a project that uses ACF composer together with Sage 10. It works great, thanks for this package.

Unfortunately I'm not perfect and sometimes forget a trailing semicolon, etc. It would be great if I can somehow `tail` an error log, but the only ones I can find in a Trellis setup (`/srv/www/domain.com/logs/`) won't show this type of errors. I'm not sure if I need to set an env variable or if this is unrelated to this package, but hopefully somebody can help me.

What's the best way to monitor PHP errors like this?

**Comment by Log1x** [comment]
Check out https://discourse.roots.io/t/log-files-not-being-created/23294/3 to re-enable error logging with the latest Acorn.

You can optionally also install `filp/whoops` alongside Acorn to use Whoops instead of Symfony.
