### ISSUE TITLE
Qraphql support 

### ISSUE THREAD

**Issue by cfab** [Log1x/acf-composer#118]
Hello, 
I'm wondering if there is a way to add generated fields to graphql (I'm using wp-graphql and wp-graphql-acf plugins).
a working fields group, if generated through the UI should have these attributes set:

```
'show_in_rest' => 1,
'show_in_graphql' => 1,
'graphql_field_name' => 'test',
'map_graphql_types_from_location_rules' => 0,
'graphql_types' => '',
```

Is there a way to do this ?
Thank you for acf-composer anyway !

edit: well that's easy !
```
$FIELD = new FieldsBuilder('POST_TYPE',[
            'show_in_rest' => 1,
            'show_in_graphql' => 1,
            'graphql_field_name' => 'xxxxx',
            'map_graphql_types_from_location_rules' => 0,
            'graphql_types' => ''
        ]);
```

**Comment by Log1x** [comment]
Glad you got it sorted!
