### ISSUE TITLE
Allow to control Field Group Settings

### ISSUE THREAD

**Issue by adminazhar** [Log1x/acf-composer#119]
After creating Fields using ACF GUI, there is option to control the Location.
But with acf-composer there is no option to control the Field Group Settings.
I wanted to change the label placement of the Field Group, but couldn't find any way to do it using acf-composer.

Is there anything i am missing, or currently acf-composer doesn't support Field Group Settings(Label Placement, Hide on Screen, Menu Order).

![image](https://user-images.githubusercontent.com/20738252/175485677-1a97c7cf-069e-4e8c-8636-f1cbac3bd53d.png)

In official ACF Documentation is there a way to do it: https://www.advancedcustomfields.com/resources/register-fields-via-php/

![image](https://user-images.githubusercontent.com/20738252/175486142-0c4427ba-8103-42a9-8a25-6bc57a8405a6.png)

**Comment by adminazhar** [comment]
Got it working by using defaults: config/acf.php
`'fieldGroup' => ['label_placement' => 'left']`

**Comment by Log1x** [comment]
Pass an array to `FieldsBuilder()`:

```php
$example = new FieldsBuilder('example', ['label_placement' => 'left']);
```

should work.

**Comment by adminazhar** [comment]
> Pass an array to `FieldsBuilder()`:
> 
> ```
> $example = new FieldsBuilder('example', ['label_placement' => 'left']);
> ```
> 
> should work.

Thanks. Closing the issue.
