### ISSUE TITLE
Should we use local-json for speed improvement?

### ISSUE THREAD

**Issue by bonakor** [Log1x/acf-composer#120]
Hi,
I'm working with ACF Composer and GraphQL. I was reading this page: https://www.advancedcustomfields.com/resources/local-json/
And it states that Local Json greatly improves performance of ACF. Is that something that I should use once the site is built?

Thank you :)

**Comment by Log1x** [comment]
Nope, ACF Composer should be all you need. I'm not certain, but I assume the reason it improves performance of ACF is it doesn't have to read the registered field groups from the database which is already the case when registering via PHP.

**Comment by bonakor** [comment]
Perfect! So it's not needed. Thank you
