### ISSUE TITLE
ACF 6.0 inline editing

### ISSUE THREAD

**Issue by brinkofblink** [Log1x/acf-composer#131]
Hi, first-off - this library is ace, thanks for working on it!

Just wondered if there's a way acf-composer can be used to provide the new ACF 6.0 editing style which happens inline rather than in the sidebar? Here's a quick screen recording to show the behaviour I mean: https://share.cleanshot.com/6Uqw8a 

Thanks,
Tom

**Comment by Log1x** [comment]
I think this is toggled by setting `$supports = ['mode' => true]`

https://github.com/Log1x/acf-composer/blob/master/src/Console/stubs/block.stub#L98

**Comment by brinkofblink** [comment]
Ah perfect, that's it - thanks for such a speedy reply.

**Comment by Log1x** [comment]
no problem
