### ISSUE TITLE
Ability to set config option for Blocks in other folders?

### ISSUE THREAD

**Issue by responsemktg** [Log1x/acf-composer#136]
I know with the composers , you could set a config option that would be loaded by $this->app->config['view.composers'] by doing something similar to this:

```php

    'composers' =>  [
            App\MyComposers\Composer::class,
    ]
```

Is there the equivalent of this for acf-composer blocks?

**Comment by Log1x** [comment]
Not at the moment but I'm not opposed to implementing it at some point.

**Comment by Log1x** [comment]
🔥
