### ISSUE TITLE
Question: how to pass through assets from bud to block preview

### ISSUE THREAD

**Issue by responsemktg** [Log1x/acf-composer#137]
I'm sure I'm missing something but I looked through all the src and couldn't figure it out.

Each of my blocks has its own entry point in Bud:

```javascript
        test: [
          "@scripts/test", 
          "@styles/test",
        ]
```

And then within my Test Block, I'm trying to get these to show when you add a block > browse all > mouse over the block for a preview.

My first thought was just to add the following inside the block file:

```javascript
public function enqueue()
{
        bundle('test')->enqueue() );
}
```

That didn't work, so I tried just adding the enqueue in here:
```javascript
public function enqueue()
{
        wp_enqueue_style( 'block-test', asset('test.css')->uri() );
        wp_enqueue_script( 'block-test', asset('test.js')->uri(), array(), '', true );
}
```

Each time, the preview loads the view with the example data - but none of the styles or scripts in the preview frame.
Looking forward to hearing what silly thing I'm missing to make this work

**Comment by Log1x** [comment]
I don't personally use the `enqueue()` method but it looks like this was ultimately broken for previews in WordPress 5.9.

https://www.advancedcustomfields.com/resources/whats-new-with-acf-blocks-in-acf-6/#asset-loading

**Comment by responsemktg** [comment]
If you don't use enqueue(), how are are you seeing the styles in the block preview when setting example content?
Or should I assume you do not use the preview functionality

**Comment by responsemktg** [comment]
I went ahead and double checked everything:

- fresh install of sage
- Wordpress 6.0.3
- Editor styles being enqueued as above
- basic styles set in the editor.css file:
```css
.example {
    background-color: purple;
    color: white;
    padding: 5px;
    margin: 5px;
}
```
- Add the class `example` to each of the list elements within the block:
```php
<div class="{{ $block->classes }}">
  @if ($items)
    <ul>
      @foreach ($items as $item)
        <li class="example">{{ $item['item'] }}</li>
      @endforeach
    </ul>
  @else
    <p>{{ $block->preview ? 'Add an item...' : 'No items found!' }}</p>
  @endif

  <div>
    <InnerBlocks />
  </div>
</div>

```

- Add the block to the page - styles work
- Rollover the block for the preview - styles do not work.
<img width="1309" alt="Screen Shot 2022-10-21 at 3 03 05 PM" src="https://user-images.githubusercontent.com/15894740/197270879-2376f040-ecf0-4794-876b-e1f62cc021cc.png">

I feel like I'm missing something really, really simple.

**Comment by Log1x** [comment]
Just tested this for you.

You need to scope the style with `.editor-styles-wrapper`

```css
.editor-styles-wrapper .example {
    background-color: purple;
    color: white;
    padding: 5px;
    margin: 5px;
}
```

**Comment by responsemktg** [comment]
@Log1x  Im guessing that you ran this using `bud build `instead of `bud dev`?
Using `bud build` will show styles, but as soon as you run `bud dev` and check again - _nothing is applied_

Ultimately - that's not a huge deal breaker as `bud build` is run before deployment - just a slight pain to deal with while running in dev move.

I really appreciate the help on this, FWIW!

**Comment by Log1x** [comment]
yeah `bud build` – I'm rarely in the editor with `bud dev` so I'm not sure about that.
