### ISSUE TITLE
No fields for location : taxonomy == category

### ISSUE THREAD

**Issue by florent-cdl** [Log1x/acf-composer#138]
Hi,

I've created a simple group field for the category taxonomy.
Unfortunately nothing appear on the new category screen
![SCR-20221022-qg0](https://user-images.githubusercontent.com/12874593/197353011-38eb1421-ad0b-4b68-bc39-1cd8ad958818.png)

My field class is however very simple

![SCR-20221022-qh0](https://user-images.githubusercontent.com/12874593/197353070-7ca45ac2-eca4-48a1-b94d-567943dfab6b.png)

My configuration : wordpres 6.0.2 / ACF 6.0.3 last version for all modules (fresh install)

A test with : ->setLocation('post_type', '==', 'post'); is ok and field appear on post screen.

Thank you

**Comment by Log1x** [comment]
I'm not sure what would be causing this but I add fields to the category taxonomy on nearly every site I have and it works as intended with code very similar to yours.

```php
<?php

namespace App\Fields;

use Log1x\AcfComposer\Field;
use StoutLogic\AcfBuilder\FieldsBuilder;

class Category extends Field
{
    /**
     * The field group.
     *
     * @return array
     */
    public function fields()
    {
        $category = new FieldsBuilder('category', ['style' => 'seamless']);

        $category
            ->setLocation('taxonomy', '==', 'category');

        $category
            ->addText('example');

        return $category->build();
    }
}
```

![Screenshot](https://i.imgur.com/CIpRIZA.png)

**Comment by Log1x** [comment]
Does it show up on the Edit screen?

It could be your screen options:

![Screenshot](https://i.imgur.com/bCO2jYk.png)

**Comment by florent-cdl** [comment]
no, not more in the edit screen. I tested your example but no field appears

**Comment by florent-cdl** [comment]
it's ok now on a new class.
I think the problem comes as I forgotten the first time to run the command "$ wp acorn vendor:publish --provider="Log1x\AcfComposer\Providers\AcfComposerServiceProvider"
I created my class before that command, so I deleted my class, run the command recreate the class with the same name and ... problem :(

Sorry and thank you so much for your quickly answer.

It's ok now, I will change my class name as it will be problematic
Best regards

**Comment by florent-cdl** [comment]
So it makes me think of one thing : is there a clean process to delete a class field ?

**Comment by Log1x** [comment]
I just delete the class file (and accompanying view if working with a Block).
