### ISSUE TITLE
How to get attributes from custom block?

### ISSUE THREAD

**Issue by sariyanta** [Log1x/acf-composer#140]
I'm new to acf-composer (and also php) and enjoy using it. 

I'm having difficulties retrieving the data from the 'Supported block features.' 

I added `'color' => 'true'` to the `$supports`. 
The changes is applied in the back-end, but couldn't figure out how to use it in the front end. 

```
	/**
	 * The supported block features.
	 *
	 * @var array
	 */
	public $supports = array(
		'align'         => true,
		'align_text'    => false,
		'align_content' => false,
		'full_height'   => false,
		'anchor'        => false,
		'mode'          => false,
		'multiple'      => true,
		'jsx'           => true,
		'color'         => true,
	);
```
Any pointer would be appreciated. 

Desar

**Comment by rleecrewmp** [comment]
In the blade file I am able to use `$block->block->textColor` and `$block->block->backgroundColor`

**Comment by sariyanta** [comment]
Perfect! 
This works! 
Thank you @rleecrewmp !
