### ISSUE TITLE
ACF Options repeater field

### ISSUE THREAD

**Issue by hallowichig0** [Log1x/acf-composer#149]
Hi, when I tried to used the options page and add a basic example of repeater. When I tried to var_dump or dd the repeater field, Example `dd(get_field('items', 'option'))` it shows a number instead of array.

**Comment by orlockz** [comment]
Hi!

Try with

get_field('items', 'option')

Note the '' around 'option'.
Also, I think 'options' works as well.

**Comment by Log1x** [comment]
I'm using multiple repeaters on an Options page with my current project without any issues.

```
get_field('example', 'options')
```

is returning an array of items.

Where are you using `get_field()`? Does it work when inside of a hook like `init` or `after_setup_theme`?

**Comment by hallowichig0** [comment]
Hi @Log1x , init solved the problem. Thank you

**Comment by Log1x** [comment]
No problem!
