### ISSUE TITLE
How to enable show_in_graphql for option page ? 

### ISSUE THREAD

**Issue by gol4nsky** [Log1x/acf-composer#155]
It is possibile to enable by default "show_in_graphql" when new option page is creating ?

**Comment by Log1x** [comment]
Not for option pages in specific (unless you edit the stub), but for all field groups you can do:

```
'fieldGroup' => ['show_in_graphql' => true],
```

inside of `config/acf.php`

**Comment by Log1x** [comment]
Are you using ACF 6.0+?

It looks like it should be `'show_in_rest' => 1`

**Comment by Log1x** [comment]
Does it work if you add it to the field group directly in your options class?

**Comment by Log1x** [comment]
Tried this myself. I'm not really sure the route/path the options page is supposed to have when registered with ACF? Is it even possible?

**Comment by Log1x** [comment]
https://support.advancedcustomfields.com/forums/topic/options-page-in-rest-api-2/#post-160315

**Comment by gol4nsky** [comment]
I'm using WPGraphQL for Advanced Custom Fields, https://github.com/wp-graphql/wp-graphql-acf#options-pages, but i guess i cant do it with acf composer so never mind, i'll do it with normal way, thank you

**Comment by gol4nsky** [comment]
I will be perfect :)

**Comment by Log1x** [comment]
Try out `composer require log1x/acf-composer:dev-master`

Add:

```php
    /**
     * The additional option page settings.
     *
     * @var array
     */
    public $settings = ['show_in_graphql' => 1];
```

to your Options class.

Let me know if that works.
