### ISSUE TITLE
Call to undefined function Log1x\AcfComposer\acf_register_block_type()

### ISSUE THREAD

**Issue by GianlucaCesari** [Log1x/acf-composer#157]
Hi, i'm using AcfComposer with sage 10 and bedrock, i have installed ACF and AcfComposer via composer and followed all the steps, vendor:publish and all. 

I can successfully run  ```wp acorn acf:block Example``` but when i try to open a page this error pops up, I tried to debug it but I dont know where to begin, anything dumb I'm missing?

Here is the stacktrace
error:
Call to undefined function Log1x\AcfComposer\acf_register_block_type()

  at /srv/www/whuis.com/current/vendor/log1x/acf-composer/src/Block.php:306
  at Log1x\AcfComposer\Block->Log1x\AcfComposer\{closure}()
     (/srv/www/whuis.com/current/vendor/log1x/acf-composer/src/Composer.php:82)
  at Log1x\AcfComposer\Composer->Log1x\AcfComposer\{closure}('')
     (/srv/www/whuis.com/current/web/wp/wp-includes/class-wp-hook.php:308)
  at WP_Hook->apply_filters(null, array(''))
     (/srv/www/whuis.com/current/web/wp/wp-includes/class-wp-hook.php:332)
  at WP_Hook->do_action(array(''))
     (/srv/www/whuis.com/current/web/wp/wp-includes/plugin.php:517)
  at do_action('init')
     (/srv/www/whuis.com/current/web/wp/wp-settings.php:623)
  at require_once('/srv/www/whuis.com/current/web/wp/wp-settings.php')
     (/srv/www/whuis.com/current/web/wp-config.php:9)
  at require_once('/srv/www/whuis.com/current/web/wp-config.php')
     (/srv/www/whuis.com/current/web/wp/wp-load.php:55)
  at require_once('/srv/www/whuis.com/current/web/wp/wp-load.php')
     (/srv/www/whuis.com/current/web/wp/wp-admin/admin.php:34)
  at require_once('/srv/www/whuis.com/current/web/wp/wp-admin/admin.php')
     (/srv/www/whuis.com/current/web/wp/wp-admin/post.php:12)

**Comment by Log1x** [comment]
Either ACF isn't activated or you're using too old of a version.

**Comment by GianlucaCesari** [comment]
I have ```"wpackagist-plugin/advanced-custom-fields":"6.1.4",``` and should be activated, should i use it as a mu-plugin or a plugin is just fine?

**Comment by Log1x** [comment]
You have to use ACF Pro for block support. It's not possible in the free version.

**Comment by GianlucaCesari** [comment]
Oh, ok, I couldn't find it in the documentation, thank you so much. Maybe it should be specified somewhere in the readme? If you want, I could draft up a pull request to update it. Let me know

G.

**Comment by Log1x** [comment]
Yeah that'd be great!

I think we could get away with just changing "ACF" to "ACF Pro" in the requirements section of the README. Option pages and other things are also locked behind Pro so it's a safe bet to probably be using Pro if using ACF Composer.

**Comment by GianlucaCesari** [comment]
I just installed ACF Pro and it was definitely that, it's now working like a charm. As soon as I have some time i'll draft a pr changing that in the documentation.
