### ISSUE TITLE
Great than character in theme template causing issues

### ISSUE THREAD

**Issue by Alex-Hay** [Log1x/acf-composer#160]
Hi there, 

A bit of an unusual one; i'm finding that using the greater than characters in quotes is removing the closing double quote (") and replacing it with a double prime character (″) – causing issues in the HTML.

.blade.php `<div class="[&>*]:mb-0"></div>` or `<div class=">"></div>`
becomes
.html `<div class="[&>*]:mb-0″></div>` or `<div class=">″></div>`

The below just causes an error.
.blade.php `<div class='[&>*]:mb-0'></div>` or `<div class='>'></div>`

This isn't the case for other template files outside of the ACF Composer template files. It only applies to `views>blocks>**.blade.php`

Thanks for your hard work on acf-composer!

**Comment by Log1x** [comment]
Interesting.

Does it happen if you set [`jsx`](https://github.com/Log1x/acf-composer/blob/master/src/Console/stubs/block.stub#L100) to `false`? 

The only thing I can think of is it being some sort of bug with how ACF parses InnerContent/jsx inside of the template.

**Comment by Alex-Hay** [comment]
Hi @Log1x, thanks for your quick response.

I tried it without jsx and the same bug occurred. I also setup a new install, adding a simple ACF block to the twentytwentythree theme and ran into the same bug – so it must be on ACF's end.

I'll submit an issue on the ACF repo, thanks for your help!

**Comment by orlockz** [comment]
I ran into the exact same problem a few days ago. I tried using ">" (larger than) in an inline javascript function. (Using alpinejs)
I couldn't understand why the closing " turned into ” on the element.

Thanks you guys. I thought I was the problem.. 😄

**Comment by Log1x** [comment]
https://github.com/AdvancedCustomFields/acf/issues/822 here's Alex's issue 💪 . I'm curious about their response. I think I've accidentally ran into this before as well.

**Comment by SergiArias** [comment]
It's a coincidence that we posted almost at the same time haha...

A workaround is to use the html entity: `&gt;` instead of `>`

**Comment by Alex-Hay** [comment]
I've just heard back from ACF on this. This seems to be an issue with wptexturize, and has popped up in a few issues:

[WordPress/gutenberg/issues/15636](https://github.com/WordPress/gutenberg/issues/15636)
[WordPress/gutenberg/pull/9963](https://github.com/WordPress/gutenberg/pull/9963)

It sounds like the ACF team are looking into a solution on there end (🤞), but it may only be resolvable in WP core.
