### ISSUE TITLE
Errors when using ">" in acf block view

### ISSUE THREAD

**Issue by SergiArias** [Log1x/acf-composer#161]
This was difficult to track, but I don't know why, when using ">" the acf block blade view fails. This doesn't happen in a regular blade view.

As an example (and using alpinejs), this fails (error: invalid character or token):
```
  <div x-data="{init() {[1,2].forEach((element)=>{console.log(element)})}}"></div>
```

Substituting the ">" for its &gt; html entity it works:
```
  <div x-data="{init() {[1,2].forEach((element)=&gt;{console.log(element)})}}"></div>
```

**Comment by Log1x** [comment]
Neat workaround.

https://github.com/Log1x/acf-composer/issues/160 was opened the other day if you missed it.

**Comment by SergiArias** [comment]
Yeah! It was a long time ago bug that I thought was a Sage problem and I just detected where it came from recently, what a coincidence that Alex also ran into the same thing! 
I close it as it is a duplicate.
