### ISSUE TITLE
On transfer to staging, no ACF blocks register

### ISSUE THREAD

**Issue by RobDobsonNC** [Log1x/acf-composer#165]
Hello - hope you can help. Probably more of a question than an issue.

I've set up a dev site and built a number of blocks using your excellent acf-composer. All is well, until I move the site to staging (using trellis deploy on Digital Ocean and moving the database over using the sync.sh script). Then - whilst I'm able to create new ACF blocks, the ones I've already created have the error:

`Your site doesn’t include support for the "acf/example" block. You can leave this block intact or remove it entirely.`

I've tried restarting the plugin, re-setting the server and starting again, restarting the full transfer again on a new install, but still no success. What is the bit I'm missing?

**Comment by mike-sheppard** [comment]
Could be an issue with the case of the filenames, seen a few folks have issues with this in the past - ie. non-case insensitive local dev, but staging has case sensitive OS. 

Not 100% the issue, but definitely worth checking - [related issue over in Roots discourse](https://discourse.roots.io/t/sage-gutenberg-and-acf-blocks/13945/67)

**Comment by RobDobsonNC** [comment]
Thanks Mike, I'll take a look.
