### ISSUE TITLE
Unable to publish the config/acf.php file

### ISSUE THREAD

**Issue by thomasjulienalain** [Log1x/acf-composer#18]
Hello ! I'm exploring Sage 10 and ACF Composer.

Every acorn commands are working fine, it's awesome !

But when i try this one to publish the acf.php config, it gives me this error : "Unable to locate publishable resources."

```
wp acorn vendor:publish --provider="Log1x\AcfComposer\Providers\AcfComposerServiceProvider"

Unable to locate publishable resources.
Publishing complete.
```

Any ideas ?

**Comment by Log1x** [comment]
Will look into this when I can. For now just grab the `config/acf.php` from the repo.

**Comment by thomasjulienalain** [comment]
Ok ! I wasn't sure if it was the same thing.

Thank you @Log1x !

**Comment by dsturm** [comment]
Publishing using `wp acorn vendor:publish --tag="acf-composer"` works, wp acorn vendor:publish --provider="Log1x\AcfComposer\Providers\AcfComposerServiceProvider" fails. 🤔

**Comment by Log1x** [comment]
Yeah I haven't had much time to check into it yet but from what I can tell it's an issue with Acorn – I'm just not exactly sure where yet.

**Comment by Log1x** [comment]
Closing this since it is a problem upstream (Acorn) – I'll push a fix in the near future.

**Comment by precisioncoder13** [comment]
have you fixed this?

I am facing the same issue while publishing using `wp acorn vendor:publish --provider="Log1x\AcfComposer\Providers\AcfComposerServiceProvider"`

I have tried with @dsturm suggestion `wp acorn vendor:publish --tag="acf-composer"` but still facing the same issue.

Error: Unable to locate publishable resources.

Thanks.
