### ISSUE TITLE
Error: PHP

### ISSUE THREAD

**Issue by mykola-havrylov** [Log1x/acf-composer#181]
Hello! I have Docker+Bedrock+Sage.

When I try to create any field I get this error. What could be the reason?

15:31:53 ❯ wp acorn acf:options ThemeOptions
Error: Your PHP installation appears to be missing the MySQL extension which is required by WordPress.
Please check that the `mysqli` PHP extension is installed and enabled.
If you are unsure what these terms mean you should probably contact your host. If you still need help you can always visit the WordPress support forums. Your PHP installation appears to be missing the MySQL extension which is required by WordPress.

**Comment by Log1x** [comment]
It sounds like you're not running commands through your Docker container. I'm afraid this isn't the place for support on local dev environments though.
