### ISSUE TITLE
How to add Multiple Field Groups at once

### ISSUE THREAD

**Issue by JUVOJustin** [Log1x/acf-composer#182]
I am looking for a way to not only define one FieldBuilder/FieldGroup at once but multiple. Since I am dynamically generating the fields i would like add them based of some terms to specific Field Groups.

My plan was to get all the terms to iterate over them, create a FieldBuilder instance for each, and then add the fields based on some logic to one of the instances. However, the fields() function of the Field Class is expected to return only one FieldBuilder instance. 

Is it possible to dynamically add multiple fieldBuilder instances?

**Comment by Log1x** [comment]
You can now return an array of Builders.
