### ISSUE TITLE
Does it work in Radicle?

### ISSUE THREAD

**Issue by lacruzwebdev** [Log1x/acf-composer#186]
Does this work in Roots Radicle? I've been following the same steps as in Sage but it seems like I can't make it work (I'm testing with an options page)

**Comment by Log1x** [comment]
There is a fix in https://github.com/roots/radicle/issues/14 – I'll see if we can figure out what the best solution is going forward so we can get that taken care of out of the box.

**Comment by lacruzwebdev** [comment]
Fix is working. Thank you.
