### ISSUE TITLE
Error when Block name is changed

### ISSUE THREAD

**Issue by Schwankenson** [Log1x/acf-composer#188]
I created this block with the acf-composer:

```
class BootstrapContainer extends Block
{
    public $name = 'Container';
    (...)
```

I want the class to be named BootstrapContainer. But the user is not interested in technical details, so $name should be just "Container". When I add this. the block content is not loaded anymore in editor. It just shows the loading wheel. Is this intended, that the block can obly be named like the class?

**Comment by Log1x** [comment]
Did you rename the view to `container.blade.php`? You would otherwise need to either set `$slug` or you could define the view path in `$view` like `blocks.bootstrap-container`

You can see what's happening here: https://github.com/Log1x/acf-composer/blob/master/src/Block.php#L325-L327
