### ISSUE TITLE
Needs update to work with Acorn 4.0

### ISSUE THREAD

**Issue by alexbogias** [Log1x/acf-composer#190]
`Class Log1x\AcfComposer\Providers\AcfComposerServiceProvider cannot extend final class Roots\Acorn\ServiceProvider`

**Comment by Log1x** [comment]
Hi. It is updated but I haven't published a release yet. For Acorn v4, you'll have to use `dev-master` for the moment.

```
composer require log1x/acf-composer:dev-master
```

**Comment by Log1x** [comment]
https://github.com/Log1x/acf-composer/releases/tag/v3.0.0
