### ISSUE TITLE
Native type hinting

### ISSUE THREAD

**Issue by codepuncher** [Log1x/acf-composer#206]
Native PHP type hints are used heavily in our agencies development instead of docblocks.
Unfortunately, we are unable to use them with `public function assets(array $block)` since it is incompatible with `Log1x\AcfComposer\Block::assets($block)`.
Do you have any plans to update the codebase to support native types?

Happy to contribute this if that is acceptable!

Thanks

**Comment by Log1x** [comment]
I'd like too but I also want to avoid forcing people to update classes. I'm not against getting it in early for `assets()` in particular though.

**Comment by codepuncher** [comment]
I've submitted a PR just for `assets()` then!
