### ISSUE TITLE
Block::getTemplate() fails on innerBlock

### ISSUE THREAD

**Issue by dsturm** [Log1x/acf-composer#212]
Since #209 `Block::getTemplate()` returns a JSON / string. Hence the `map()` callback in https://github.com/Log1x/acf-composer/blob/a49708259ae1228f70e247d937c70f5d1e95c37c/src/Block.php#L339-L341 will fail at calling `->all()` on a string.

I'm currently not sure, whether we need the `->all()` in the callback.

**Comment by Log1x** [comment]
Re-reading 209 again, I'm slightly confused by the initial issue. `$template` doesn't get cached.

**Comment by dsturm** [comment]
Unfortunately, I had not tested the issue mentioned by @djaevlen. As a quickfix, if I ditch the `->all()` in the callback, it works. But I'm not sure, whether all possible template data of a block would convert correctly.

**Comment by Log1x** [comment]
i should have a fix in a few minutes

**Comment by Log1x** [comment]
> The block (acf/button) that mainly have the issue is using a addPartial.

let me know if this still happens on .10
