### ISSUE TITLE
Using Custom Field Type Aliases

### ISSUE THREAD

**Issue by mike-sheppard** [Log1x/acf-composer#217]
hey @Log1x tried using `addEditorPalette('my_field')` but get a no function exists error.

### Steps

1. Updated ACF config `wp acorn vendor:publish --tag="acf-composer"`
2. Uncommented `'editorPalette' => 'editor_palette',` in acf.php config
3. Generated the IDE helpers `wp acorn acf:ide-helpers`
4. Replaced a field to test
    ```diff
    - ->addField('footer_text', 'editor_palette')
    + ->addEditorPalette('footer_text')
    ```

### Error
```
No such function: addEditorPalette
```

Am I missing a piece of the puzzle?

### Notes

`advanced-custom-fields-pro` & `log1x/acf-editor-palette` are installed as mu-plugins

**Comment by Log1x** [comment]
😓

**Comment by mike-sheppard** [comment]
whey! 🎉 all good now (since `v3.0.13`), thanks! 🙌
