### ISSUE TITLE
Custom Field Type Aliases within Repeaters

### ISSUE THREAD

**Issue by mike-sheppard** [Log1x/acf-composer#219]
Hey @Log1x, sorry for pestering -this should be the last one hopefully. 🤞 

Looks like the custom aliases throw an error in Repeater fields.

### Error
```
No such function: endRepeater
```
![2024-02-29 1444 - Arc](https://github.com/Log1x/acf-composer/assets/1690006/f8d8bafe-02a5-4422-a4d5-c981271e9f87)

### Example
```diff
$block->addAccordion('illustration_links')
    ->addRepeater('links')
-        ->addField('text_color', 'editor_palette')
+        ->addEditorPalette('text_color')
-        ->addField('background_color', 'editor_palette')
+        ->addEditorPalette('background_color')
    ->endRepeater()
;
```

**Comment by Log1x** [comment]
no sorry needed. let me know if you stumble across anything else.

**Comment by mike-sheppard** [comment]
perfecto! 👌 All working well my side (_medium-ish sized project with a fair amount of fields_), thanks again! 🙏
