### ISSUE TITLE
Dont cache fields in development env?

### ISSUE THREAD

**Issue by djaevlen** [Log1x/acf-composer#236]
Is it possible to disable caching of fields in development env? Everytime I make a change to a field I need to run `wp acorn acf:cache` for it to apply my changes. 

I tried to set the manifest path to null but no luck:

```php
[
     'manifest' => WP_ENV === 'development' ? null : storage_path('framework/cache'),
]
```

**Comment by Log1x** [comment]
You can clear it with `acf:clear` – it doesn't automatically cache itself.

**Comment by djaevlen** [comment]
Ahhh my understanding from the docs, was that it would automatically cache itself on every field change.
Makes sense now, thank!
