### ISSUE TITLE
How to enable usePostMeta in ACF Block

### ISSUE THREAD

**Issue by joseph-farruggio** [Log1x/acf-composer#248]
How can I enabled `usePostMeta` for ACF Blocks generated with the ACF Composer?

**Comment by Log1x** [comment]
try adding it to https://github.com/Log1x/acf-composer/blob/master/src/Console/stubs/block.stub#L100

**Comment by joseph-farruggio** [comment]
I tried that, but I don't believe it belongs inside of supports.

If this were going inside of block.json, then it would go under the acf key.

**Comment by Log1x** [comment]
oh i see, it needs to be in the `acf` key. https://www.advancedcustomfields.com/resources/save-acf-block-values-to-post-meta/

it needs a PR to go [here](https://github.com/Log1x/acf-composer/blob/master/src/Block.php#L533-L536) for `block.json` but would need to source dive to see if it works when registered with PHP

**Comment by Log1x** [comment]
looks like it can be done with `use_post_meta` when passed to settings for non-cached blocks. it would make sense to introduce a new `$postMeta` bool to enable this probably

**Comment by joseph-farruggio** [comment]
Is there a supported way of manually passing in `use_post_meta` from my block's controller?

**Comment by Log1x** [comment]
not in this case, but if you want to do a PR I can get it merged in and push a release. otherwise I can swing around to this sometime this week.

**Comment by Log1x** [comment]
Would you mind giving #249 a try when you get a chance?

**Comment by joseph-farruggio** [comment]
Sorry for the delay. This is what I needed. Thanks
