### ISSUE TITLE
Widget ID & ACF data missing

### ISSUE THREAD

**Issue by mike-sheppard** [Log1x/acf-composer#25]
Hey @Log1x, thanks again for the awesome package. I've just moved onto generating a few widgets  but can't seem to access any ACF field data, it looks like the widget id is blank.

### Steps to reproduce
1. `$ wp acorn acf:widget Example`
1. Add the widget, title & list items  

Output: Missing `title` & `No items found!`

---

### Possible solution

I've had a quick look and it seems adding 
```php
$this->widget->id = 'widget_' . Arr::get($args, 'widget_id');
``` 

within the [widget() render method](https://github.com/Log1x/acf-composer/blob/master/src/Widget.php#L133) fixes it, but not entirely sure that's the right place to set it?

Also perhaps changing `$this->widget->id` to `$this->id` in [widget.stub:L43](https://github.com/Log1x/acf-composer/blob/master/src/Console/stubs/widget.stub#L43) & [widget.stub:L73](https://github.com/Log1x/acf-composer/blob/master/src/Console/stubs/widget.stub#L73) ?

Cheers!

**Comment by Log1x** [comment]
Will look into this ASAP - its more than likely related to `$this->widget` being defined inside of the filter.

As far as `$this->id` I kept it more so for compatibility - I switched back to `$this->widget->id` in the stubs at one point as I felt it was less confusing along with wanting to make people aware of `$this->widget` without having to reference it in docs.

**Comment by Log1x** [comment]
https://github.com/Log1x/acf-composer/tree/log1x/bugfixes I've started on this here but I'm getting trolled a bit due to hook ordering – I'll fix it today/tomorrow as it's about to get in my way on my current project.

**Comment by mike-sheppard** [comment]
nice one, thanks! not sure if I can be of any help, but give me a shout if there is anything, testing etc
