### ISSUE TITLE
Default $supports values

### ISSUE THREAD

**Issue by joseph-farruggio** [Log1x/acf-composer#251]
Is it possible to change the default values within $supports when generating a new block?

**Comment by Log1x** [comment]
You should be able to publish the stubs with `wp acorn acf:stubs` and then delete any you aren't customizing. Let me know if it doesn't work.

**Comment by Log1x** [comment]
I do think it'd be a nice feature in the future to make the stubs more dynamic so they could be configured in the `acf-composer.php` config. Maybe a nice feature to do once Acorn v5 is out as I'd like to deprecate Acorn v3 so I can use `laravel/prompts` in CLI since it requires PHP 8.1.

**Comment by Log1x** [comment]
This is done in #278 for #253 and will be merged when Acorn v5 is released. 👍
