### ISSUE TITLE
How to retrieve the anchor or the ID of a block in blade

### ISSUE THREAD

**Issue by cataras** [Log1x/acf-composer#255]
Hello,

Thanks for your great work.

Is there a way to retrieve the block anchor or ID? I can't find the information anywhere.

Is there the equivalent of $block-classes for anchors?

Thanks in advance,

**Comment by Log1x** [comment]
hey, no problem. that kinda stuff will be on `$block->block` inside of the view, so `$block->block->anchor`

**Comment by cataras** [comment]
Thank you so much @Log1x! It seems so simple!
And congratulations again on your great work!
