### ISSUE TITLE
Block enqueue assets 

### ISSUE THREAD

**Issue by chrisbakr** [Log1x/acf-composer#256]
I'm enqueuing block assets with the following method:

 `public function assets($block)
  {
    bundle('blocks/HeroBlock')->enqueue();
  }`
  
The assets are loaded but inside WP admin with Sage10 the editor.js is not loaded anymore. Also it has a different behaviour in dev and build mode.

**Comment by Log1x** [comment]
You're going to have to Google `acf composer blocks bud discourse` or something and just research the multitude of different threads that have come up to configure Bud to handle this situation along with it's Runtime. I value my sanity too much to do something like this so I have no examples to share.
