### ISSUE TITLE
Best practise for Flexible Content

### ISSUE THREAD

**Issue by simondotwhite** [Log1x/acf-composer#257]
Hey,

Looking through some of the code and issues it seems like #175 is the most up to date information it. But in the [code](https://github.com/Log1x/acf-composer/blob/master/src/Concerns/InteractsWithPartial.php#L18), it says that `$this->get()` is deprecated. 

Is there a better/more up-to-date way of adding partials as layouts when using Flexible Content? 

Cheers

**Comment by Log1x** [comment]
It should be simplified to `$example->partial(YourPartial::class)` now.

**Comment by Log1x** [comment]
Oh, I think you can just pass the partial straight to `->addLayout` now the same as my partial example above: https://github.com/Log1x/acf-composer/blob/284c40b61e6efeea0995f1c0951c9606b7d021e1/src/Builder/FlexibleContentBuilder.php#L64-L75

Sorry, I never use Flexible Content anymore so I couldn't entirely remember.

**Comment by Log1x** [comment]
Also, assuming all works well – we can probably get a rule for that in the upgrade command.

https://github.com/Log1x/acf-composer/blob/master/src/Console/UpgradeCommand.php#L49

**Comment by simondotwhite** [comment]
Hey, thanks for coming back to me. When I try to pass the partial class in like this

```php
->addLayout(Text::class)
```
It wasn't working. Although the following does, so maybe I've misunderstood. 


```php
class PageBuilder extends Partial
{
    public function fields()
    {
        $pageBuilder = Builder::make('pageBuilder');

        $pageBuilder
            ->addFlexibleContent('components', ['label' => 'Blocks'])
            ->addLayout('Text')->addPartial(Text::class)
            ->endFlexibleContent();

        return $pageBuilder;
    }
}
```

Thanks for your help!

**Comment by Log1x** [comment]
Ah I see. It's good the latter works – but I think we can make it a bit better in the future. 👍
