### ISSUE TITLE
$loop variable not working

### ISSUE THREAD

**Issue by smeedijzer-internet** [Log1x/acf-composer#26]
Hi,

It seem like the [$loop](https://laravel.com/docs/7.x/blade#loops) variable isn't available. I can't figure out why, shouldn't it be available?

```
@if ($items)
  <ul>
    @foreach ($items as $item)
      {{$loop->count}}
    @endforeach
  </ul>
@else
  <p>No items found!</p>
@endif
```

**Comment by Log1x** [comment]
yeah it should. what kind of field? I'm going to try to push a fix for widgets today that might be related

**Comment by smeedijzer-internet** [comment]
I figured it out, I returned the data wrong way. Now it's working as expected!
