### ISSUE TITLE
Is it possible to limit the color palette per block?

### ISSUE THREAD

**Issue by znikap** [Log1x/acf-composer#260]
I was wondering if instead of taking all the colors from the theme.json (being generated with tailwind):
``` php
$supports = [
        'color' => [
            'background' => true,
            'text' => true,
            'gradient' => true,
       ],
];
```

you could define the colors you want to be available, so for example:
``` php
$supports = [
        'color' => [
            'background' => ['red-500', 'blue-500'],
            'text' => true
            'gradient' => true,
       ],
];
```

Is there any workaround to achieve that? So you could limit the colors per block?

**Comment by Log1x** [comment]
doesn't look like it. https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/#color
