### ISSUE TITLE
Issues running acorn commands

### ISSUE THREAD

**Issue by kinglouie** [Log1x/acf-composer#262]
I tried using this plugin with the latest `roots/sage` dev release today. Unfortunately I'm getting some weird errors:

1. `wp acorn vendor:publish --tag="acf-composer"` return the following:
` INFO  No publishable resources for tag [acf-composer].  `
I then created the `acf.php` manually

2. when running `wp acorn acf:field Example` i get the following error:
`PHP Fatal error:  Declaration of Monolog\Logger::emergency(Stringable|string $message, array $context = []): void must be compatible with Psr\Log\LoggerInterface::emergency($message, array $context = []) in /app/wordpress/wp-content/themes/boeckenholt/vendor/monolog/monolog/src/Monolog/Logger.php on line 682`

I would really appreciate some insight where the issues may be originating from :) Thanks for the great package btw! In a former project I did not have these issues.

## env info
php 8.1 docker container
roots/sage  10.x-dev
log1x/acf-composer": ^3.0
roots/acorn: ^4.3

**Comment by Log1x** [comment]
Looks like you have some clash of deps. Make sure Acorn/ACF Composer are installed alongside each other in the same Composer file and you don't have any overlapping dependencies.

Otherwise, this is not an issue with ACF Composer.
