### ISSUE TITLE
Changed behaviour of get_queried_object

### ISSUE THREAD

**Issue by RobMaple** [Log1x/acf-composer#264]
Sorry if this is a bit vague but I've run into an issue after upgrading from version 2 to 3 that seems to effect the behaviour of get_queried_object. 

I have a taxonomy archive page that also allows filtering posts by a secondary taxonomy and term - the URL structure looks like:
https://example.com/taxonmy_a/term?taxonomy_b=term

Using version 2 of acf-composer, get_queried_object returns the term of taxonomy_a as I would expect whereas when using version 3, get_queried_object now returns the term of taxonomy_b.

I'm not quite sure why thats happening but for now I've rolled back to v2 -- is there something I've not considered about the updated functionality?

**Comment by Log1x** [comment]
you can try tweaking the priority on https://github.com/Log1x/acf-composer/blob/master/src/AcfComposer.php#L101 – is it a custom taxonomy?

**Comment by RobMaple** [comment]
Thanks for the suggestion, no luc with tweaking the priority though.
Yes both taxonomies are custom.

**Comment by Log1x** [comment]
You're going to have to give more info then. How are they custom? How are you registering them? What hooks are they in? Even if you change from `acf/init` to `init` on that hook, it has the same affect? Are you sure your post types/taxonomies are being registered in a proper hook?

**Comment by RobMaple** [comment]
Yeah sure. So one taxonomy, the 'route' one in the URL structure mentioned, is actually a woocommerce tax 'product_cat' ( sorry mistakenly thought it was custom for some reason ). The other taxonomy is custom and registered using poet (2.1.0) - this is also registered against the woocommerce 'product' post type.

This is the poet config for that tax: 

```
'collection' =>
            [
                'links' => 'product',
                'label' => __('Collections'),
                'rewrite' => ['slug' => 'collection', 'with_front' => false],
                'hierarchical' => true,
                'show_in_rest' => true,
                'meta_box_cb' => 'post_categories_meta_box',
                'show_ui' => true,
                'show_in_nav_menus' => true,
            ],
```

In terms of the get_queried_object call, that happens in a sage view component class that is used to filter products by both taxonomy terms in some specific instances.

Not sure if that helps -- happy to share more ocde if necessary. I've tried changing acf/init to init but no luck with that either. Will take a look through the diff tomorrow for any more clues.

**Comment by Log1x** [comment]
I'm not really sure, especially without seeing any of the object code.

Perhaps try tweaking [this change](https://github.com/Log1x/poet/commit/537649337e6a628991cf10effde1d9e34fbe3a27) from Poet?

I find this all a little strange as the combined changes with the latest Poet and ACF Composer v3 increased compatibility for me quite a bit, especially when trying to dynamically create fields inside of field groups/blocks – but I also do everything in my power to avoid WooCommerce. 😆

**Comment by RobMaple** [comment]
Had a chance to take another look this morning and turns out switching the poet hookPriority to 5 fixes the issue. 
I'd mistakely assumed it was the major version bump of acf-composer that was the issue but actually the minor version change of poet that was causing the issue.

**Comment by Log1x** [comment]
If you add `'hookPriority' => 5` into your `poet.php` config it should fix your issue. If I get more reports of this I'll explore other options – but this seems to be a weird quirk with WooCommerce and will otherwise cause issues with having post types/taxonomies registered in time to be able to query them while dynamically creating field types.
