### ISSUE TITLE
Custom Block Icon

### ISSUE THREAD

**Issue by Tartamata** [Log1x/acf-composer#265]
Hi,

I'm hoping to get some guidance on incorporating custom SVG icons into ACF Composer blocks within Sage 10.

Currently, I'm using the following approach:

`public $icon = '<svg></svg>';
`
This method works, but it becomes cumbersome to maintain, especially when the same icon appears across multiple blocks or if the SVG code is lengthy.

Ideally, I'd like to leverage the asset directive to link these icons. Is there a supported way to achieve this within ACF Composer?

Thanks in advance for your assistance!

**Comment by Log1x** [comment]
Hey! I'll be sure to add support for this in ACF Composer v4. No ETA yet, though.

**Comment by Log1x** [comment]
Support for this is added. Check https://github.com/Log1x/acf-composer/pull/277 for an example.
