### ISSUE TITLE
Set position of field group to the side

### ISSUE THREAD

**Issue by DarkSideRacer** [Log1x/acf-composer#279]
Hi,

is there any way to set the position of a field (or field group) to the editor sidebar? By default it shows the fields below the content. I'm trying to set it up on a field but it doesn't work:

```
        $pages = Builder::make('pages');

        $pages
            ->setLocation('post_type', '==', 'page');

        $pages
            ->addText('subtitle', [
                'label' => 'Subtitle',
                'position' => 'side'
            ]);

        return $pages->build();
```

**Comment by Log1x** [comment]
Try `Builder::make('pages', ['position' => 'side'])` – its at the very bottom of the [cheatsheet](https://github.com/Log1x/acf-builder-cheatsheet?tab=readme-ov-file#field-group-position).

**Comment by DarkSideRacer** [comment]
Thanks, that worked!

Sorry, never reached the bottom of the cheatsheet, always clicked on the anchor links :) there's some useful stuff there

**Comment by Log1x** [comment]
no problem! glad it worked 😄
