### ISSUE TITLE
Advanced Custom Fields does not appear to be activated.  

### ISSUE THREAD

**Issue by chantalreijerkerk** [Log1x/acf-composer#280]
How can I activate it? When I create a field, I get this 🎉 ExampleOptions option successfully composed every time.
⮑ app/Options/ExampleOptions.php

WARN Advanced Custom Fields does not appear to be activated.

But this is not visible in the backend

**Comment by Log1x** [comment]
Make sure https://www.advancedcustomfields.com/pro/ is installed and activated.
