### ISSUE TITLE
Passing params to a partial?

### ISSUE THREAD

**Issue by astray-heavy-arms** [Log1x/acf-composer#283]
This is more a question than anything else.

If I generate a field partial that contains: -

text
image
relationship

Then say I use that partial in two diffrent blocks that need the relationship in one to reference post_type `foo` and the second block post type `bar`.

When using a partial how do I change the post types of the relationship field between my blocks?

**Comment by Log1x** [comment]
You should be able to use [`modifyField`](https://github.com/Log1x/acf-builder-cheatsheet?tab=readme-ov-file#modifying-fields) – I think this will work:

```php
$field
    ->addPartial(Partials\Review::class)
    ->modifyField('advertiser_url', [
        'post_type' => ['bar'],
    ]);
```
