### ISSUE TITLE
Blocks do not render/unavailable in Patterns

### ISSUE THREAD

**Issue by qbattersby** [Log1x/acf-composer#292]
When I create a block and then use it on a page, and create a pattern from that block it fails to load/render in the Patterns editor. 

Using Sage 10 (no Bedrock). In my testing block is called Testimonials. Here is the error I get going to Appearance -> Patterns and choosing the Pattern.

Your site doesn’t include support for the "acf/testimonials" block. You can leave it as-is, convert it to custom HTML, or remove it.

Thoughts?

<img width="634" alt="Screenshot 2024-12-17 at 2 20 19 PM" src="https://github.com/user-attachments/assets/1ddb56d1-4ebd-4834-a878-e53277664519" />

<img width="1375" alt="Screenshot 2024-12-17 at 2 20 26 PM" src="https://github.com/user-attachments/assets/92722dcd-5d58-4c66-9352-282ccd466f69" />

**Comment by Log1x** [comment]
Thanks for the report! I think this might've already been fixed but a release wasn't pushed yet. Can you try v3.2.1?

**Comment by qbattersby** [comment]
Amazing, I see the only change there is it uses the default array for parent and ancestor, which I understand is optional or could be null. 

In another project I am using this package by @MWDelaney to create ACF blocks and it has the exact same problem. I know this is not your project but thought you may have insight on how I may apply this fix to this project as well. I believe it is abandoned generally speaking. But thought I may try asking. https://github.com/MWDelaney/sage-acf-wp-blocks

I figure in that package passing parent and ancestor as null may do the trick on/about line 95? https://github.com/MWDelaney/sage-acf-wp-blocks/blob/master/sage-acf-gutenberg-blocks.php

**Comment by Log1x** [comment]
> I figure in that package passing parent and ancestor as null may do the trick on/about line 95?

I think in ACF Composer's case it was because it was explicitly setting it as `null` - I don't see it being set at all in that package so I don't think it'd cause any issues.
