### ISSUE TITLE
All custom blocks disappeard on 3.2.1

### ISSUE THREAD

**Issue by maxleistner** [Log1x/acf-composer#293]
Ugrading from 3.2.0 to 3.2.1 leads to an unknown error which removes all custom blocks from the sidebar. 
Can you confirm?

https://github.com/Log1x/acf-composer/compare/v3.2.0...v3.2.1

**Comment by Log1x** [comment]
Which version of ACF Pro?

**Comment by maxleistner** [comment]
> Which version of ACF Pro?

6.3.11

**Comment by Log1x** [comment]
Does explicitly setting your `$parent` and `$ancestor` props to `null` instead of `[]` fix it?

**Comment by maxleistner** [comment]
> Does explicitly setting your `$parent` and `$ancestor` props to `null` instead of `[]` fix it?

yes it does. But default generation output is [] - so i guess everyone is using it

**Comment by Log1x** [comment]
very strange. perhaps we just dont set these at all unless they aren't empty. this was just changed in https://github.com/Log1x/acf-composer/pull/288

**Comment by Log1x** [comment]
Pushed a release, let me know if it worked.
