### ISSUE TITLE
Block post type restriction doesn't work on cached blocks

### ISSUE THREAD

**Issue by thunderdw** [Log1x/acf-composer#295]
Cached blocks don't currently respect the post type restriction on the block properties.

To reproduce:
- Restrict a block to a given post type(s):
   ```php
   /**
    * The block post type allow list.
    *
    * @var array
    */
   public $post_types = ['page', 'resource'];
   ```
- Edit a post of another post type and the block will not be available.
- Run `wp acorn acf:cache` and reload the editor. The block is now available.

This happens because the `post_types` property is an ACF property but is currently set in the root of the generated `block.json`:
```json
{
    "name": "acf\/related-content",
    "title": "Related Content",
    "description": "Related Content block",
    "category": "custom",
    "icon": "align-left",
    "post_types": [
        "page",
        "resource"
    ],
    "supports": {
...
```

The post types key should be renamed to `postTypes` and nested in the `acf` key: https://www.advancedcustomfields.com/resources/acf-block-configuration-via-block-json/

Pushing a PR shortly to fix this.

**Comment by Log1x** [comment]
appreciate the PR!
