### ISSUE TITLE
Null Coalesce Operator on Array renders false in view

### ISSUE THREAD

**Issue by tylerwiegand** [Log1x/acf-composer#3]
In my experience, ACF tends to return false instead of null. In your stubs you end up passing false to the view instead of the empty array for items. I almost did a pull request, but I thought maybe theres a reason you're doing this, or you handle this differently at some other point.

Anyways, it confused me for awhile since I assumed the 
```
get_field('items) ?? [];
```
would have worked, but for me
```
get_field('items) ?: [];
```
seems to work with ACF more consistently...but it would be nice to have a "ACF didnt find that field" return null instead of false...

I didn't fully realize what was happening until I dumped everything that was being passed to the view
```
{{ dd(get_defined_vars()['__data']) }}
```

Anyways, having tons of fun with the package, really dig being able to treat Sage 10 mostly like a laravel project!! =)

**Comment by Log1x** [comment]
I think you're right, `?:` would probably be more sane. Would you like to do a PR for the stubs?

**Comment by tylerwiegand** [comment]
Yesssssss

**Comment by tylerwiegand** [comment]
https://github.com/Log1x/acf-composer/commit/9fde72f74022f15ebb90e295ead285e04a4b215a
