### ISSUE TITLE
Post ID not available

### ISSUE THREAD

**Issue by mike-sheppard** [Log1x/acf-composer#32]
Hey @Log1x 👋 

Might be an obvious solution I'm missing, but is there a way to get the current `$post->ID` in the Blocks? It works ok on the frontend but not in the admin preview. It seems acf-composer is hooked pretty early on so not of the post stuff has been populated yet, at a guess?

Bit of context - I'm making a recommended posts section and need to exclude the current post from the query. User can choose between custom selection (relationship) or latest feed from selected categories.

```php
...
    public function with()
    {
        return [
            'query' => $this->get_posts_query(),
        ];
    }

    public function get_posts_query() 
    {
        $feed = get_field('feed');

        $defaults = [
            'posts_per_page'  => 5,
            'post_status'     => 'publish',
        ];

        if ($feed === 'category') {
            if ($cat_ids = get_field('categories')) {
                $args['category__in'] = $cat_ids;
            }

            if ($current_post_id = get_the_id()) { // <-- Need the post ID here, if possible?
                $args['post__not_in'] = [$current_post_id]; // exclude the current post
            }
        }

        if ($feed === 'custom') {...}

        $query_args = wp_parse_args($args, $defaults);
        $query = new \WP_Query($query_args);

        return $query;
    }
```

Cheers!

**Comment by mike-sheppard** [comment]
ahh after a bit more digging it's available from: `$this->post`! 🤦

**Comment by mike-sheppard** [comment]
One little thing I was thinking would it make sense to update `$post` to `$post_id` https://github.com/Log1x/acf-composer/blob/master/src/Block.php#L200

```diff
- public function render($block, $content = '', $preview = false, $post = 0)
+ public function render($block, $content = '', $preview = false, $post_id = 0)
```

And  https://github.com/Log1x/acf-composer/blob/master/src/Block.php#L205
```diff
- $this->post = $post;
+ $this->post_id = $post_id;
Or
+ $this->post = get_post($post_id);
```

**Comment by Log1x** [comment]
I can get behind that. I'll toss it in when I go to finish #28

**Comment by capellopablo** [comment]
@mike-sheppard @Log1x I noted that the post ID is available in the method with()... but.. How can I get the post ID before that?

I'm trying to auto populate a field with the post meta data. So I need that the post ID be available in fields() method.
Example:

`public function fields()
    {
        $legacyBlock = new FieldsBuilder('legacy_block');

        $legacyBlock
            ->addSelect('legacyBlock', [
                'choices' => $this->legacyBlocks(),
            ])
            ;

        return $legacyBlock->build();
    }`

`public function legacyBlocks()
    {
        // I need the post ID in the next line. I tried with: $this->post | $_POST['post_id'] | $_REQUEST['post'] | $_GET['post'] 
        $blocks = get_field('blocks', $this->post );
        $legacyBlocks = $var;
        if ( is_array( $blocks ) && count($blocks) > 0 ) {
            $legacyBlocks = [];
            foreach ( $blocks as $block ) {
                if ( isset( $block['acf_fc_layout'] ) ) {
                    $legacyBlocks[] = $block['acf_fc_layout'];
                }
            }
        }

        return $legacyBlocks;
    }`


At that point, $this->post is not defined. 
I tried with $this->post | $_POST['post_id'] | $_REQUEST['post'] | $_GET['post'] but none of them works.

Any idea how can I get it?

**Comment by Log1x** [comment]
hmm usually `$_GET['post']` would get you the current ID while editing a post – but I haven't done this in awhile.

**Comment by capellopablo** [comment]
Yes, I thought the same. It actually works if I do a wp_die() in the method.
But it doesn't work on the reactivity of the block.

**Comment by capellopablo** [comment]
Just FYI 
I tried with this:
![Captura de Pantalla 2020-11-05 a la(s) 18 06 46](https://user-images.githubusercontent.com/7504518/98296441-ad1cd900-1f91-11eb-99c3-5f320991c7c3.png)

And I got this: 
![Captura de Pantalla 2020-11-05 a la(s) 18 07 14](https://user-images.githubusercontent.com/7504518/98296477-bd34b880-1f91-11eb-9dad-aa48dcb4ed27.png)

Conclusion:
$_GET and $_REQUEST work if you die the execution, but they don't in the reactive interactions.
$_POST doesn't work if you die the execution, but it works in the reactive interactions.
