### ISSUE TITLE
isReservedName does not exist

### ISSUE THREAD

**Issue by linsjb** [Log1x/acf-composer#33]
Hi Log1x. Awesome package i must say. Really looking forward to try it out!
I have a problem tho.
When i try setup a field, block, widget etc. with Acorn I get the following error:
```
In Macroable.php line 103:
Method Log1x\AcfComposer\Console\FieldMakeCommand::isReservedName does not exist. 
```
Don't really know if it's a problem with acf-composer or any other problem. 

Thanks in advance!

**Comment by Log1x** [comment]
Can you try running `composer upgrade` and make sure all of the illuminate dependencies are up to date on Sage 10?

**Comment by linsjb** [comment]
Dang, that was a fast respons! 
Yes that solved the issue! It sure bumped up the version of illuminate a bit. From 7.11 to 7.21.
Sometimes the solution is way to simple.
Thank you so much! :)
