### ISSUE TITLE
Duplicate Widget ID

### ISSUE THREAD

**Issue by mike-sheppard** [Log1x/acf-composer#36]
Hey @Log1x thanks for fixing up those other bits, much appreciated. Just run into this weird one today - not sure if it's the way I'm calling `get_field()` maybe? But trying out the `Example` widget it appears to have the same issue.

**Summary**

Multiple widgets return the same `widget_id` so ACF data returned is always the last widget added (of the same type).

**Example**

1. `wp acorn acf:widget Example`
1. Add 2 or more Example widgets with a few unique list items <img width="448" alt="Screenshot 2020-08-04 at 16 11 39" src="https://user-images.githubusercontent.com/1690006/89311108-79b66f80-d66d-11ea-8dc3-24e382357322.png">
1. Identical fields will be shown in the view (last added widget) <img width="731" alt="Screenshot 2020-08-04 at 16 07 07" src="https://user-images.githubusercontent.com/1690006/89311119-7cb16000-d66d-11ea-8ac4-0cc5736df02e.png">

**Comment by Log1x** [comment]
If you change `https://github.com/Log1x/acf-composer/blob/master/src/Providers/AcfComposerServiceProvider.php#L39` to `$this->app->bind` – does it work?

**Comment by mike-sheppard** [comment]
Thanks for looking into this Looks like the result is the same as before with this change:

```php
$this->app->bind('AcfComposer', function () {
    return $this->compose();
});
```

**Comment by mike-sheppard** [comment]
My guess was something to do with the passed `$instnance` - https://github.com/Log1x/acf-composer/blob/master/src/Widget.php#L125 but haven't dived in too deep yet, should be able to spend some time on it this eve.

**Comment by Log1x** [comment]
man I'm a little stumped on this. it has something to do with the proper variables not passing when initializing the anonymous class. there has to be a way to make it properly work

**Comment by mike-sheppard** [comment]
So got a hacky 'fix'..

Setting the id from the instance/args seems to fix it? https://github.com/Log1x/acf-composer/blob/master/src/Widget.php#L125
```diff
public function widget($args, $instance)
{
+   $this->widget->widget->id  = "widget_{$args['widget_id']}";
    echo Arr::get($args, 'before_widget');
```
