### ISSUE TITLE
Translatable block name and description

### ISSUE THREAD

**Issue by smeedijzer-internet** [Log1x/acf-composer#44]
Hi,

Is it possible to make the block name translatable?

This isn't working:
public $name = __('DummyClass', 'text-domain');

**Comment by Log1x** [comment]
You should be able to set `$this->name` inside of a `__construct()` instead

**Comment by davideprevosto** [comment]
I am using the version 3.x of ACF Composer.

I used this code into an Option acf field:

```
public function __construct(AcfComposer $composer)
{
     parent::__construct($composer);
     $this->name = _x('Options Page', 'options', 'radicle');
     $this->title = _x('Options Page | Options', 'options', 'radicle');
}
```

I hope I did the right thing and that it will be useful to those who are trying to solve the same 'problem'.
