### ISSUE TITLE
Custom post type ?

### ISSUE THREAD

**Issue by Androlax2** [Log1x/acf-composer#54]
Hey,

Do you think it would be a good idea to add custom post type ? something like acf:cpt (I can make a PR if you think it could be useful). Maybe it could works like the Widget, but without the view => I don't know if we can add the view directly with cpt

**Comment by Log1x** [comment]
Can you elaborate on what you mean for the CPT?

**Comment by Androlax2** [comment]
> Can you elaborate on what you mean for the CPT?
> 
> Would https://github.com/log1x/poet be relevant?

I was thinking about a thing like that yes but with ACF here, is that relevant for you in this plugin ?

**Comment by Log1x** [comment]
I'm going to pass on this. Unless I don't understand what you have in mind, it doesn't seem worthwhile to maintain on top of Poet.
