### ISSUE TITLE
Wrong case slug

### ISSUE THREAD

**Issue by smeedijzer-internet** [Log1x/acf-composer#57]
@Log1x

I found that the slug generates invalid when creating a new block with 'multiple words':

wp acorn acf:block TestBlock --construct

https://github.com/Log1x/acf-composer/blob/7f5c506e92a38ebb892d318068dc36e95e6b938a/src/Console/stubs/block.construct.stub#L16

Results in `test_block`. 

I tried replacing `DummySnake` with `DummySlug`, which gives: `testblock`. This works, but I think adding it as `test-block` is beter.

I found that DummyKebab isn't present in [Acorn](https://github.com/roots/acorn/blob/fa60ba1551dc96400b10aaa7f396a2fffd62e5c6/src/Acorn/Console/Commands/GeneratorCommand.php#L38).

I'm not sure if this required changes in Acorn or can be done an other way. What do you think?

**Comment by Log1x** [comment]
I removed all of the non-Laravel replacement slugs from Acorn since we wanted to thin up the code-base and not add any extra overhead.

That being said, I'll have to fix this in Command.php
