### ISSUE TITLE
Enancement: Pass through array of blocks that live in other locations?

### ISSUE THREAD

**Issue by responsemktg** [Log1x/acf-composer#58]
**Scenario:** We build themes that pull from a repo of blocks, that are folders outside the app directory, which are self contained components:
```
MyBlocks
|- Block.php
|- view.blade.php
|- admin.css
|- style.css
|- script.js
|- config.js
```

**Issue:** Currently, the compose method scans folders for php files, which gets tripped up if a blade file also lives in the same directory.

**Suggestion:** It would be great it we could pass through an array of namespaces to compose as blocks within the `AcfComposerServiceProvider.php` similar to how the `config/views.php` file handles an additional composers array/

The `config/acf.php` file could have something similar to:
```
    'defaults' => [
        'trueFalse' => ['ui' => 1],
        'select' => ['ui' => 1],
    ],

    'composers' => [       

    ],
```

Which you could pass your namespaces:
```
    'defaults' => [
        'trueFalse' => ['ui' => 1],
        'select' => ['ui' => 1],
    ],

    'composers' => [       
        'MyBlocks\Header',
        ...
        'MyBlocks\Features',
    ],
```

And the `AcfComposerServiceProvider.php` could have something along the lines of (this is really rough)
```
        foreach($this->app->config['acf.composers'] as $composer) {
            if (
                is_subclass_of($composer, Composer::class) &&
                ! is_subclass_of($composer, Partial::class) &&
                ! (new ReflectionClass($composer))->isAbstract()
            ) {

                $this->fields[] = (new $composer($this->app))->compose();
            }
        }
```

Just a thought.

**Comment by Log1x** [comment]
Related: #63

**Comment by Log1x** [comment]
Will add array support in #63 for
