### ISSUE TITLE
Undefiend method when adding any field after ->endRepeater() 

### ISSUE THREAD

**Issue by theMosaad** [Log1x/acf-composer#60]
When calling any field adding method on `->endRepeater()` like the example below
```php
$example
    ->addRepeater('items')
        ->addTextarea('item')
    ->endRepeater()
    ->addText('text');
```
The Intelephense says `Undefined method 'addText'.` And it stops prompting the available methods, previewing their documentation, ..etc. 

This wasn't the case when using ACF Builder directly with Sage 9.

A workaround I'm currently using is calling the methods on the instance itself as shown below
```php
$example
    ->addRepeater('items')
        ->addTextarea('item')
    ->endRepeater();

$example
    ->addText('text');
```
However, this gets a little annoying when the variable name is long and I have to copy it every time I add a Repeater. On the other hand, calling methods on `->endGroup()` works as expected.

I have the time to contribute to fixing this issue if you're aware of it and/or can direct me to the right path.

**Comment by Log1x** [comment]
🤔 I'm actually not 100% sure why this is happening.

**Comment by theMosaad** [comment]
Will try to figure it out

**Comment by theMosaad** [comment]
Turns out it's a problem with StoutLogic/acf-builder which I submitted a pull request to fix https://github.com/StoutLogic/acf-builder/pull/130

**Comment by Log1x** [comment]
good catch!
