### ISSUE TITLE
Add-ons support?

### ISSUE THREAD

**Issue by Twansparant** [Log1x/acf-composer#61]
Hi there,

Great plugin! Can't wait to use it in every project now.
I've got one simple question though, if you're using any [3rd party add-on](https://www.advancedcustomfields.com/add-ons/), like for instance the [Font Awesome Field](https://wordpress.org/plugins/advanced-custom-fields-font-awesome/).

How would I add a field for that with your builder?
I can see the field type for that is `font-awesome`, but using `addFontAwesome` does not work:

```php
->addFontAwesome('icon', [
	'label'           => 'Icon',
	'instructions'    => 'Select an icon',
	'required'        => 1,
	'save_format'     => 'class',
	'allow_null'      => 0,
	'show_preview'    => 1,
	'enqueue_fa'      => 1,
	'fa_live_preview' => ''
])
```
and results in an error:
```
"No such function: addFontAwesome"
```

Do I need to define this somewhere?
Thanks a lot!

**Comment by mike-sheppard** [comment]
it'll be something along the lines of:

```php
->addField('font-awesome', 'icon')
```

**Comment by Log1x** [comment]
Semi-related, I plan on attempting support for doing this via a magic method in a future release.

**Comment by Twansparant** [comment]
Thanks both! Did not find that myself
