### ISSUE TITLE
some addFlexibleContent options don't work

### ISSUE THREAD

**Issue by theMosaad** [Log1x/acf-composer#64]
The below works with sage 9 and  "stoutlogic/acf-builder": "1.10.0"
Errs with "log1x/acf-composer": "v1.5.5" which is using the same "stoutlogic/acf-builder" version
location: `/vendor/log1x/acf-composer/src/Composer.php : 109`
```php
$builder
    ->addFlexibleContent('sections', [
        'acfe_flexible_layouts_thumbnails' => 1, // "array_map(): Expected parameter 2 to be an array, int given"
        'acfe_flexible_layouts_state' => 'collapse', // "array_map(): Expected parameter 2 to be an array, string given"
    ]);
```
Wanted to check if you have any clues before I give it a shot.

**Comment by Log1x** [comment]
hmm I'm not sure outside of checking what it'd expect in terms of an array instead of the int and string.

are you using the log1x/next branch on Sage 10? if so, I might need to make some adjustments to the error handler. it's being a little aggressive I noticed.

**Comment by theMosaad** [comment]
Had the same issue with the master branch of roots/sage. Only difference is that the error didn't stop web pages, only appeared when running wp cli. However, it didn't enable thumbnails for flexible content like what acf-builder did with sage 9.

What I don't get is that other options with string and int work fine such as the below:
```php
$builder
    ->addFlexibleContent('sections', [
        'acfe_flexible_advanced' => 1,
        'acfe_flexible_stylised_button' => 1,
        'acfe_flexible_clone' => 1,
        'acfe_flexible_close_button' => 1,
        'acfe_flexible_modal_edition' => 0,
        'acfe_flexible_modal' => [
            'acfe_flexible_modal_enabled' => '1',
            'acfe_flexible_modal_title' => 'Add Section',
            'acfe_flexible_modal_col' => '4',
            'acfe_flexible_modal_categories' => '1',
        ],
        'button_label' => 'Add Section'
    ])
```

**Comment by theMosaad** [comment]
Found it! https://github.com/Log1x/acf-composer/pull/65
