### ISSUE TITLE
WP Acorn

### ISSUE THREAD

**Issue by fabianwurk** [Log1x/acf-composer#68]
Hey Brandon, 

I'm trying to install this package for Sage10. I'm testing it locally, but getting a 'command not found' for this:

`wp acorn vendor:publish --provider="Log1x\AcfComposer\Providers\AcfComposerServiceProvider"`

Is there something else that needs to be installed for wp acorn commands?

Thanks

**Comment by fabianwurk** [comment]
Had to add WP CLI on Laptop 🙈. So able to run command now but got this:

```
Unable to locate publishable resources.
Publishing complete.
```
Is that a normal notification for this?

**Comment by fabianwurk** [comment]
All seems to be working fine anyway so will close this issue.

**Comment by Log1x** [comment]
You might have to do `wp acorn vendor:publish` and then select ACF Composer from the list
