### ISSUE TITLE
Running yarn build:production breaks gutenberg preview width

### ISSUE THREAD

**Issue by fabianwurk** [Log1x/acf-composer#69]
Brandon if I run a **yarn build**, the gutenberg container is correct at the fixed size I've created for the block eg:
```
.wp-block {
  max-width: 896px;
}
```
<img width="1179" alt="Screenshot 2021-02-24 at 23 44 43" src="https://user-images.githubusercontent.com/18347097/109081659-88906c80-76fa-11eb-8434-d054f12e4af7.png">

but when I run a **yarn production:build**, I'm only getting container width of 580px - any ideas why this might happen?

<img width="1175" alt="Screenshot 2021-02-24 at 23 44 07" src="https://user-images.githubusercontent.com/18347097/109081694-93e39800-76fa-11eb-961e-7c6d55c3f78f.png">

(FYI its Sage 10)

Thanks,

Fabian

**Comment by Log1x** [comment]
is it the latest sage 10? is it getting purged?

**Comment by fabianwurk** [comment]
Yeah Brandon, was been purged 🥴 so whitelisted the class in webpack, and all good. Thanks 👍
