### ISSUE TITLE
Installing gives me `Unable to locate publishable resources.`

### ISSUE THREAD

**Issue by StudioRATATA** [Log1x/acf-composer#70]
Hi! 
I'm unable to install this package.

- `composer require log1x/acf-composer` (no errors)
- `wp acorn vendor:publish --provider="Log1x\AcfComposer\Providers\AcfComposerServiceProvider"`  (returns error)

The console renders: 
```
Unable to locate publishable resources.
Publishing complete.
```

I can see the folder in `vendor/`

**Comment by Log1x** [comment]
run just `wp acorn vendor:publish` and select it from the list

**Comment by stuartcusackie** [comment]
I tried this and the package appeared in the list, however I ran into this error:

```
In VendorPublishCommand.php line 277:
Call to undefined function Illuminate\Foundation\Console\base_path()
```

**Comment by devbaze** [comment]
composer self-update --1 will fix all your problem :D
