### ISSUE TITLE
Block preview issue while using Alpine.js in Gutenberg

### ISSUE THREAD

**Issue by fabianwurk** [Log1x/acf-composer#74]
Brandon do you know if there is an issue with using Alpine.js within blocks? I've just added a simple alpine code block to an acf composer block view file eg:

```
<div class="{{ $block->classes }}">

  <div x-data="{ count: 1 }">
    <p x-text="count"></p>
    <button @click="count++">Count Up</button>
    <button @click="count--">Count Down</button>
  </div>

  <div>
    <InnerBlocks />
  </div>
</div>
```
It no longer allows the block to preview in Gutenberg?

<img width="1412" alt="Screenshot 2021-03-02 at 16 41 08" src="https://user-images.githubusercontent.com/18347097/109682547-6d987f00-7b76-11eb-8fd7-6469b6b71d63.png">

**Comment by Log1x** [comment]
Alpine and React don't play nice together in the backend. If you get it working I'm interested.

**Comment by fabianwurk** [comment]
Yeah, thought there may be a conflict. I'll have a deeper dig to see if I can find out more, and maybe test with Vue too. Will keep you posted.

**Comment by fabianwurk** [comment]
I think JSX is the troublemaker - see this article: https://codewithhugo.com/alpine-js-react/

So, can disable it via on block:

```
    public $supports = [
       ............
        'jsx' => false,
    ];
```
But not sure what knock on effect that might have 🧐

**Comment by Log1x** [comment]
It'd prevent the use of `<InnerBlocks />`

**Comment by fabianwurk** [comment]
Suppose its a bit of a trade-off, with using Alpine or Inner Blocks - can't imagine using both together, so this method is a viable workaround.

**Comment by dsturm** [comment]
I would rather use the `$block->preview` attribute to conditionally include the Alpine directives. Furthermore you should avoid use event shorthand `@click` and instead use `x-on:click` to prevent issues coming from blade directives. So in this example:

```php
<div class="{{ $block->classes }}">

  <div @if (!$block->preview) x-data="{ count: 1 }" @endif>
    <p @if (!$block->preview) x-text="count" @endif></p>
    <button x-on:click="count++">Count Up</button>
    <button x-on:click="count--">Count Down</button>
  </div>

  <div>
    <InnerBlocks />
  </div>
</div>
```
