### ISSUE TITLE
Problem with starting ACF-Composer with Sage10

### ISSUE THREAD

**Issue by grzesiek1owline** [Log1x/acf-composer#75]
Hi, I have a problem running this tool.
I'm using Sage 10, I have ACF Pro 5.9.5 installed
My installation process:
1. Run `composer require log1x/acf-composer`
2. Run `wp acorn vendor:publish` and check 1 [[1] Provider: Log1x\AcfComposer\Providers\AcfComposerServiceProvider
]
3.  Run `wp acorn acf:field Example` and `wp acorn acf:options Options`

Tool create files in `app/Options` and `app/Fields` directory but they are not visible in the Wordpress admin panel.

**Comment by noonanwebgroup** [comment]
This could be related to #71 and #73. I was having the same issue where the files were being generated but ACF wasn't picking them up.

Perhaps @Log1x could add a new release which includes these fixes?

**Comment by noonanwebgroup** [comment]
@grzesiek1owline it looks like a new release has been published, so try updating and see if that now works.

**Comment by grzesiek1owline** [comment]
After update everything is ok. Thanks!
