### ISSUE TITLE
Poet with ACF Composer Block Category Issues

### ISSUE THREAD

**Issue by conradfuhrman** [Log1x/acf-composer#76]
Using Poet to register items and custom block categories on v2.0.0

Block categories looks like:
```
'block_categories' => [
    'customer_blocks' => [
        'title' => 'Customer Blocks',
        'icon' => 'star-filled',
    ],
],
```

In ACF Composer v2.0.2 the blocks I've created have this defined under the category variable:

```
/**
* The block category.
*
* @var string
*/
public $category = 'customer_blocks';
```

However everything just shows up under the text block category in the WordPress (5.6.2) admin. The other items from poet register properly so I'm probably missing something in translation here. Any thoughts?

**Comment by mike-sheppard** [comment]
@conradfuhrman thing it's just `categories`, give this a try:

```php
'categories' => [
    'customer_blocks' => [
        'title'  => 'Customer Blocks',
        'icon'   => 'star-filled',
    ],
],
```

**Comment by conradfuhrman** [comment]
I thought that too but that didn't work either. Possibly order of operations?

**Comment by Log1x** [comment]
There was a typo in the README. It's supposed to be `block_category`, not `block_categories`.
