### ISSUE TITLE
Troubles with including partials...

### ISSUE THREAD

**Issue by minemindmedia** [Log1x/acf-composer#77]
First of all, thanks so much for all your hard work with these packages for Sage 10. I am just beginning to dive into your toolsets and I am having an issue with including files.

First of all, I have Gutenberg disabled on purpose. I still prefer the old editor.

I've generated a `Page.php` file located in `app/Fields/Page.php` and here's the code:

```
<?php

namespace App\Fields;

use Log1x\AcfComposer\Field;
use StoutLogic\AcfBuilder\FieldsBuilder;

class Page extends Field
{
    /**
     * The field group.
     *
     * @return array
     */
    public function fields()
    {

        $page = new FieldsBuilder('page');

        $page
            ->setLocation('post_type', '==', 'page');
        
        $page
            ->addFields($this->get(General::class));

        return $page->build();


    }
}

```
On my home page, this becomes visible:

![image](https://user-images.githubusercontent.com/8854361/112361262-d320ec80-8c98-11eb-9eb6-e6e5b36910e8.png)

Next, I've generated a `General.php` page located at `app/Fields/Partials/General.php` and here's the code:

```
<?php

namespace App\Fields\Partials;

use Log1x\AcfComposer\Partial;
use StoutLogic\AcfBuilder\FieldsBuilder;

class General extends Partial
{
    /**
     * The partial group.
     *
     * @return array
     */
    public function fields()
    {
        $general = new FieldsBuilder('general');

        $general
            ->addTab('general', ['placement' => 'left'])
                ->addTrueFalse('enable_social_sharing', ['ui' => 1])
                    ->setDefaultValue('1')
                    ->setInstructions('Shows social sharing buttons for various platforms below the title.')
                    
                ->addTrueFalse('enable_featured_image', ['ui' => 1])
                    ->setDefaultValue('1')
                    ->setInstructions('Enables automatically displaying the featured image before the content.');
                    
        return $general;
    }
}
```
But nothing more appears on the admin pages other than the image I attached above.

The documentation I am following is a mix of these which I am not sure they're all up to date:

https://roots.io/guides/using-acf-builder-with-sage/

https://github.com/Log1x/acf-composer

https://github.com/Log1x/acf-builder-cheatsheet#flexible-content

**Comment by mike-sheppard** [comment]
try adding `use App\Fields\Partials\General;` to the top of `app/Fields/Page.php`

**Comment by minemindmedia** [comment]
Whelp, yep, that solved it. Thanks. Sorry I missed that.

While I am here, is there anyway to toggle off items? I'd like to remove the standard content editor for example.

**Comment by mike-sheppard** [comment]
Think it's usually done when registering a post type - https://developer.wordpress.org/reference/functions/register_post_type/

Don't include the `editor` in the `supports` arrray and you should be good!

Also, if in the sage10 world, check out - https://github.com/log1x/poet#registering-a-post-type

**Comment by minemindmedia** [comment]
Excellent. I've yet to work with Poet but do plan on it soon.

Any idea what this is for then?
https://github.com/Log1x/acf-builder-cheatsheet#removing-fields

**Comment by minemindmedia** [comment]
I have another question. I am having issues getting flexible content setup.

Here's my code:

```
<?php

namespace App\Fields\Partials;

use Log1x\AcfComposer\Partial;
use StoutLogic\AcfBuilder\FieldsBuilder;

class Builder extends Partial
{
    /**
     * The partial group.
     *
     * @return array
     */
    public function fields()
    {
        $builder = new FieldsBuilder('builder');

        $builder
        ->addFlexibleContent('flexible_content_field', [
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => [],
            'wrapper' => [
              'width' => '',
              'class' => '',
              'id' => '',
            ],
            'button_label' => 'Add Row',
            'min' => '',
            'max' => '',
        ]);
    
        $builder
            ->addLayout('layout', [
                'label' => 'Layout',
                'display' => 'block',
                'sub_fields' => [],
                'min' => '',
                'max' => '',
            ]);
        
        $builder
            ->addLayout(new FieldsBuilder());
                    
        return $builder;
    }
}
```

That's a partial included in my page.php file.

If I add all the code from the docs like I have done above, nothing shows up.

If I remove the addLayout sections, like so:
```

<?php

namespace App\Fields\Partials;

use Log1x\AcfComposer\Partial;
use StoutLogic\AcfBuilder\FieldsBuilder;

class Builder extends Partial
{
    /**
     * The partial group.
     *
     * @return array
     */
    public function fields()
    {
        $builder = new FieldsBuilder('builder');

        $builder
        ->addFlexibleContent('flexible_content_field', [
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => [],
            'wrapper' => [
              'width' => '',
              'class' => '',
              'id' => '',
            ],
            'button_label' => 'Add Row',
            'min' => '',
            'max' => '',
        ]);
                    
        return $builder;
    }
}
```

Then it will produce this:

![image](https://user-images.githubusercontent.com/8854361/112380160-aaa3ed00-8cae-11eb-9cce-e5973af9b702.png)

I can't figure out how to add layouts. Everything disappears once I attempt to.

**Comment by mike-sheppard** [comment]
> Any idea what this is for then?
> https://github.com/Log1x/acf-builder-cheatsheet#removing-fields
> 

removing/modifying fields setup via acf-composer/builder.

**Comment by mike-sheppard** [comment]
This line is unnecessary + probs breaking it


```php
$builder
    ->addLayout(new FieldsBuilder());
```
