### ISSUE TITLE
Basic Example Field

### ISSUE THREAD

**Issue by ineptian** [Log1x/acf-composer#78]
Big thanks to log1x for all of these great WP/Roots helpers.

I am having some trouble getting the basic example repeater field to show up on the front end of my front page. The fields show up great on the page in the back end, and I have some basic text in the fields. I know that I am probably just doing something wrong in one of the steps. Hoping one of you great people can help my dumbass out.

Here is what I have right now:

app > Fields > Example.php
```
<?php

namespace App\Fields;

use Log1x\AcfComposer\Field;
use StoutLogic\AcfBuilder\FieldsBuilder;

class Example extends Field
{

    /**
     * The field group.
     *
     * @return array
     */
    public function fields()
    {
        $example = new FieldsBuilder('example');

        $example
            ->setLocation('page_template', '==', 'template-page-home.blade.php');

        $example
            ->addRepeater('items')
                ->addText('item')
            ->endRepeater();

        return $example->build();
    }
}
```

views > fields > example.blade.php
```
@if ($items)
  <ul>
    @foreach ($items as $item)
      <li>{{ $item['item'] }}</li>
    @endforeach
  </ul>
@else
  <p>No items found!</p>
@endif
```

views > template-page-home.blade.php
```
@include('fields.example')
```
When including it on my front page, I just get a blank page back. I am thinking it might have to do something with either the namespace (does the field folder need to be outside the view??), or possibly I am not using the fields in the way they are intended?

Any help on this would be much appreciated, been banging my head against the wall for a while now trying to figure it out. Feel like its something super simple and I am just being an idiot.

Thanks!

**Comment by Log1x** [comment]
Fields don't work like blocks in terms of having a view auto-magically available.

You'd just use regular 'ol `get_field('example')` in your view or a Composer/Component.

**Comment by ineptian** [comment]
Awesome. That is easy enough. So what I have above would work if I was creating a component/block, but does not work for the basic field?

Thanks!!
