### ISSUE TITLE
Partials working locally, but not in production

### ISSUE THREAD

**Issue by fowlercraig** [Log1x/acf-composer#96]
I've got a couple partials in a field and they work as they should when I'm developing locally. 

When I deploy to staging/production, they're not appearing at all. Anything I should look out for? 

I've tried with Kinsta and DigitalOcean, but no luck.

**Comment by Log1x** [comment]
Not sure what would be causing this. It only happens with partials? Can you show an example?

**Comment by fowlercraig** [comment]
```
<?php

namespace App\Fields;

use Log1x\AcfComposer\Field;
use StoutLogic\AcfBuilder\FieldsBuilder;
use App\Fields\Partials\Builder;
use App\Fields\Partials\Image;

class LayoutBuilder extends Field
{
    /**
     * The field group.
     *
     * @return array
     */
    public function fields()
    {
        $layoutBuilder = new FieldsBuilder('layout_builder',[
            'hide_on_screen' => ['the_content']
        ]);

        $layoutBuilder
            ->setLocation('page_template', '==', 'page-builder.blade.php');

        $layoutBuilder
        ->addFields($this->get(Image::class));

        return $layoutBuilder->build();
    }
}

```

**Comment by fowlercraig** [comment]
I think I figured it out – it appears that the case of these guys need to match the file they're referencing 

`use App\Fields\Partials\Image;`
`->addFields($this->get(Image::class));`

In my case should be

`use App\Fields\Partials\image;`
`->addFields($this->get(jmage::class));`

Not sure why my local installation is more forgiving than production, but cest la vie

**Comment by Log1x** [comment]
I've had the same problem with local being more forgiving. Not sure why – but glad you got it figured out!

**Comment by broskees** [comment]
I'm having this same issue. Only in my case no case issue that I can find.
