### ISSUE TITLE
Problem after update ACF to version 5.11 - get_field() return null

### ISSUE THREAD

**Issue by grzesiek1owline** [Log1x/acf-composer#97]
After the last update of ACF PRO to version 5.11, there was a problem with reading the fields.
I cannot read the values ​​of some fields. The return is NULL.

example in functions.php
```
$account_page = (is_array($account_page)) ? $account_page['url'] : $home_url;
define('ACCOUNT_PAGE', $account_page);
```

The same is the case with the php script that handles the form
```
session_start();

include 'vendor/autoload.php';
use Hybridauth\Hybridauth;

$google_login = (get_field('google-login-api', 'option')) ?? null;
```

How to fix this in acf-composer?

Issue in ACF GH - [get_field returns null after upgrading to v5.11 · Issue #570 · AdvancedCustomFields/acf](https://github.com/AdvancedCustomFields/acf/issues/570)

I tried to change the priority in the register() function on acf composer, but unfortunately to no avail.

**Comment by Log1x** [comment]
what about changing the `init` hook to `acf/init` and removing the priority?

**Comment by grzesiek1owline** [comment]
After change `init` to `acf/init` my options pages are broken, and not show in admin panel.
Now i change `get_field('xyz', 'option')` to `get_option('xyz')` and this way everything is ok.

I have this solution from roots discourse - [this post](https://discourse.roots.io/t/acf-5-11-problem-with-get-field-from-options/21705/2)

**Comment by ahmedch1** [comment]
> After change `init` to `acf/init` my options pages are broken, and not show in admin panel. Now i change `get_field('xyz', 'option')` to `get_option('xyz')` and this way everything is ok.
> 
> I have this solution from roots discourse - [this post](https://discourse.roots.io/t/acf-5-11-problem-with-get-field-from-options/21705/2)

Is this solution still accurate in December 2022 , time of writing this comment ?
Thanks

**Comment by Log1x** [comment]
Retrieving ACF fields using `get_option()` is not ideal because they will not return in the proper format.

If you're experiencing this problem, you should check that you are using `get_field()` inside of a hook (e.g. `after_setup_theme`, a view/template, or a view composer.

**Comment by ahmedch1** [comment]
> after_setup_theme

Thanks for your answer , I am using Sage 9 , you mean I use it in setup.php file of sage theme ?
Thanks in advance

**Comment by Log1x** [comment]
> you mean I use it in setup.php file of sage theme ?

You'd have to show an example of your code, but yes – make sure what you're retrieving/doing is inside of a hook. `setup.php` or `filters.php` should be fine depending on what you're doing.

**Comment by ahmedch1** [comment]
This is the code snippet related to acf_add_local_field_group in my project : 
```
if( class_exists('acf') ){
	if(is_admin()){
		add_action('init', function () {
			collect(glob(config('theme.dir').'/app/fields/*.php'))->map(function ($field) {
				return require_once($field);
			})->map(function ($field) {
				if ($field instanceof FieldsBuilder) {
					acf_add_local_field_group($field->build());
				}
			});

		});
	}else{
		add_action('wp', function () {
			collect(glob(config('theme.dir').'/app/fields/*.php'))->map(function ($field) {
				return require_once($field);
			})->map(function ($field) {
				if ($field instanceof FieldsBuilder) {
					acf_add_local_field_group($field->build());
				}
			});

		});
	}

}
```
Thanks for your help

**Comment by Log1x** [comment]
What's the code related to your problem with `get_field`? (e.g. where is it returning null?)

**Comment by ahmedch1** [comment]
It is very strange that I can't figure out where the problem exactly is established as I am getting this error 
`Notice: acf_get_value was called incorrectly. Advanced Custom Fields PRO - We've detected one or more calls to retrieve ACF field values before ACF has been initialized. This is not supported and can result in malformed or missing data. [Learn how to fix this](https://www.advancedcustomfields.com/resources/acf-field-functions/?utm_source=ACF+PRO&utm_medium=insideplugin&utm_campagin=docs&utm_content=early_init_warning). Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 5.11.1.) in C:\______wp-includes\functions.php on line 5663`

Thanks a lot for taking your time to help

**Comment by Log1x** [comment]
Yeah I'm not sure how to help. Did you do a global search for `acf_get_value` and see where it's being used?

**Comment by ahmedch1** [comment]
Sure but it is only located in the plugin folder theme  under :
app/plugins/advanced-custom-fields-pro
(I am using Sage 9 with ACF Pro 6 )
